### ISSUE TITLE
Templates compatibility with VS2022

### ISSUE THREAD

**Issue by mdomurad** [engthiago/Onboxframework#6]
Hello,
thanks for sharing this great framework.

Are templates compatible with VS2022? 

For me, they don't appear after installation.

**Comment by engthiago** [comment]
Hey thank you.. I have never tried on vs2022, did you try to drop the templates on its folder?

**Comment by mdomurad** [comment]
I managed to resolve this issue - after installing the latest update of VS2022 templates appeared. Thanks.

**Comment by engthiago** [comment]
Nice! Thanks for letting me know
